apiVersion: hermes.agent/v1
kind: HermesInstance
metadata:
  labels:
    app.kubernetes.io/name: hermes-operator
    app.kubernetes.io/managed-by: kustomize
  name: hermesinstance-sample
spec:
  # TODO(user): Add fields here
